name: 'Desplegar PostgreSQL en EC2'

on:
  workflow_dispatch:

jobs:
  deploy:
    name: 'Desplegar Contenedor PostgreSQL'
    runs-on: ubuntu-latest 

    steps:
      - name: 'Conectar a EC2 y desplegar contenedor'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop postgresql-dev || true
            docker rm postgresql-dev || true

            docker run -d \
              --name postgresql-dev \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              -p 5432:5432 \
              postgres:15